use_frameworks!

platform :ios, '8.0'

target 'DynamicLaunchImage_Example' do
  pod 'DynamicLaunchImage', :path => '../'

  target 'DynamicLaunchImage_Tests' do
    inherit! :search_paths

    
  end
end
